### ISSUE TITLE
Categorizing OM STRI and Jiggins-Meier images into categories for segmentation

### ISSUE THREAD

**Issue by ramirezmichelle** [Imageomics/slicerMorph_JSON_generator#9]
Categories include:

- Body attached: butterfly images where wings are still attached to body
- Damaged wings: noticeable/extreme damage to wing quality
- Incomplete wing set: less than 4 wings photographed
- Small wings: unusually small wing size, may be merged into "damaged wings"
- Has color palette: images that contain color palette
- Other Dorsal View: dorsal view of butterfly wings that don't fit into categories above
- Other Ventral view: ventral view of butterfly wings that don't fit into categories above

**Comment by hlapp** [comment]
I think this was meant for a different repo?

**Comment by ramirezmichelle** [comment]
yes it was, my bad. Thank you

**Comment by hlapp** [comment]
No worries. BTW I can transfer it to the repo of your choice.

**Comment by ramirezmichelle** [comment]
Ah fixed it already, but I appreciate it! Thanks
